import json
import html
from datetime import datetime
from typing import Dict, Any, List

class HTMLReportGenerator:
    def __init__(self, agent_state: Dict[str, Any]):
        self.state = agent_state
        self.title = "SciLink Research Report"
        self.generated_by = "Generated by SciLink Planning Agent"
        
    def _get_css(self) -> str:
        return """
        <style>
            :root { 
                --primary: #2563eb; 
                --bg: #f8fafc; 
                --card-bg: #ffffff; 
                --code-bg: #1e293b;
                --success-bg: #f0fdf4; --success-border: #bbf7d0; --success-text: #166534;
            }
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #334155; background: var(--bg); margin: 0; padding: 40px; }
            .container { max-width: 1000px; margin: 0 auto; }
            
            /* Header */
            header { background: var(--card-bg); padding: 30px; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 40px; border-bottom: 4px solid var(--primary); }
            h1 { margin: 0; color: #1e293b; font-size: 2em; }
            .meta { color: #64748b; font-size: 0.9em; margin-top: 10px; font-family: monospace; }
            .objective { background: #eff6ff; border-left: 4px solid var(--primary); padding: 15px; margin-top: 20px; color: #1e40af; }
            
            /* Timeline Cards */
            .card { background: var(--card-bg); border-radius: 12px; padding: 0; margin-bottom: 40px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); overflow: hidden; }
            .card-header { padding: 15px 25px; background: #f1f5f9; border-bottom: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; }
            .card-header h2 { margin: 0; font-size: 1.2em; color: #475569; }
            .badge { padding: 4px 10px; border-radius: 20px; font-size: 0.75em; font-weight: bold; text-transform: uppercase; letter-spacing: 0.05em; }
            .badge.plan { background: #dbeafe; color: #1e40af; }
            .badge.tea { background: #d1fae5; color: #065f46; }
            .card-body { padding: 25px; }

            /* Content Sections */
            .exp-block { margin-bottom: 30px; border-left: 3px solid #e2e8f0; padding-left: 20px; }
            .justification { background: #fffbeb; color: #92400e; padding: 10px; border-radius: 6px; font-style: italic; font-size: 0.95em; }
            
            pre { background: var(--code-bg); color: #e2e8f0; padding: 15px; border-radius: 8px; overflow-x: auto; font-family: 'Menlo', 'Monaco', monospace; font-size: 0.85em; }
            .result-box { margin-top: 20px; padding: 20px; background: var(--success-bg); border: 1px solid var(--success-border); border-radius: 8px; color: var(--success-text); }
            
            /* TEA Specific */
            .tea-list li { margin-bottom: 8px; }
            .cost { color: #b91c1c; }
            .benefit { color: #047857; }
        </style>
        """

    def _render_experiment(self, exp: Dict[str, Any], index: int) -> str:
        code_html = ""
        # Only render code if it exists (Final version will have it)
        if "implementation_code" in exp:
            code_html = f"""
            <div style="margin-top:15px;">
                <strong>💻 Generated Code:</strong>
                <pre><code>{html.escape(exp['implementation_code'])}</code></pre>
            </div>
            """
            
        return f"""
        <div class="exp-block">
            <h4 style="color: #2563eb; margin-bottom: 5px;">Experiment {index}: {html.escape(exp.get('experiment_name', 'Unnamed'))}</h4>
            <div style="margin-bottom: 10px;"><strong>🎯 Hypothesis:</strong> {html.escape(exp.get('hypothesis', ''))}</div>
            
            <div class="justification">
                <strong>💡 Justification:</strong> {html.escape(exp.get('justification', ''))}
            </div>
            
            <div style="margin-top: 15px;">
                <strong>🧪 Steps:</strong>
                <ul>{''.join(f"<li>{html.escape(s)}</li>" for s in exp.get('experimental_steps', []))}</ul>
            </div>
            {code_html}
        </div>
        """

    def _render_tea(self, plan: Dict[str, Any]) -> str:
        assess = plan.get('technoeconomic_assessment', {})
        def list_to_html(key, css_class):
            return "".join(f"<li class='{css_class}'>{html.escape(str(x))}</li>" for x in assess.get(key, []))

        return f"""
        <div class="exp-block" style="border-left-color: #10b981;">
            <div class="justification" style="background: #ecfdf5; color: #065f46;">
                <strong>💰 Executive Summary:</strong> {html.escape(assess.get('summary', ''))}
            </div>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px;">
                <div><strong>💸 Key Cost Drivers:</strong><ul class="tea-list">{list_to_html('key_cost_drivers', 'cost')}</ul></div>
                <div><strong>📈 Potential Benefits:</strong><ul class="tea-list">{list_to_html('potential_benefits_or_revenue', 'benefit')}</ul></div>
            </div>
            <div style="margin-top: 15px;"><strong>⚠️ Economic Risks:</strong><ul>{list_to_html('economic_risks', '')}</ul></div>
        </div>
        """

    def generate(self, output_path: str):
        date_str = self.state.get('start_time', datetime.now().isoformat())
        
        # --- 1. FILTERING LOGIC ---
        # We process the full 'plan_history' (which contains drafts, corrections, etc.)
        # and distill it down so that each Iteration # only appears ONCE (the latest version).
        
        full_history = self.state.get('plan_history', [])
        finalized_plans = {}
        
        for plan in full_history:
            # We use 'iteration' as the unique key. 
            # Since we are iterating chronologically, the LAST entry for a specific iteration
            # will overwrite previous drafts. This ensures the HTML only shows the Final Plan.
            iter_idx = plan.get('iteration', 0)
            finalized_plans[iter_idx] = plan

        # Convert back to sorted list for rendering
        sorted_plans = [finalized_plans[k] for k in sorted(finalized_plans.keys())]
        
        results = self.state.get('experimental_results', [])

        # --- 2. RENDER HTML ---
        html_content = f"""
        <!DOCTYPE html><html><head><meta charset="UTF-8"><title>{self.title}</title>{self._get_css()}</head>
        <body><div class="container">
            <header>
                <h1>🔭 {self.title}</h1>
                <div class="meta">Session: {self.state.get('session_id', 'N/A')} &bull; Started: {date_str}</div>
                <div class="objective"><strong>Objective:</strong> {html.escape(self.state.get('objective', ''))}</div>
            </header>
        """

        for i, plan in enumerate(sorted_plans):
            # Display numbering (1, 2, 3...)
            step_num = i + 1 
            
            is_tea = "technoeconomic_assessment" in plan or plan.get("type") == "technoeconomic_analysis"
            badge_class = "tea" if is_tea else "plan"
            badge_text = "TECHNO-ECONOMIC ANALYSIS" if is_tea else "EXPERIMENTAL STRATEGY"
            
            if is_tea:
                content_html = self._render_tea(plan)
            else:
                content_html = "".join(self._render_experiment(exp, x+1) for x, exp in enumerate(plan.get('proposed_experiments', [])))

            html_content += f"""
            <div class="card">
                <div class="card-header">
                    <h2>Step {step_num}</h2>
                    <span class="badge {badge_class}">{badge_text}</span>
                </div>
                <div class="card-body">{content_html}"""

            # Render Matching Results (if any)
            # Logic: If we are at Step 1 (sorted index 0), we look for results[0]
            if i < len(results):
                res_data = results[i].get('data_summary', '')
                try:
                    if isinstance(res_data, str) and (res_data.strip().startswith('{') or res_data.strip().startswith('[')):
                        res_data = json.dumps(json.loads(res_data), indent=2)
                except: pass
                
                html_content += f"""
                    <div class="result-box">
                        <div style="font-weight:bold; margin-bottom:10px;">📊 Results Received:</div>
                        <pre style="background:none; color:inherit; padding:0;">{html.escape(str(res_data))}</pre>
                    </div>
                """

            html_content += "</div></div>"

        html_content += f"<footer><p>{self.generated_by}</p></footer></div></body></html>"

        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            print(f"  - 📄 HTML Report updated (Final Views Only): {output_path}")
        except Exception as e:
            print(f"  - ❌ Error writing HTML report: {e}")